apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-storage
spec:
  storageClassName: "nginx"
  capacity:
    storage: 500
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: nginx-pvc
  gcePersistentDisk:
    pdName: gke-pv
    fsType: ext4
